--Run your code to create the stored procedure.

SELECT SCHOOL_ID, NAME_OF_SCHOOL, LEADERS_SCORE, LEADERS_ICON
FROM CHICAGO_PUBLIC_SCHOOLS
LIMIT 1;

CALL UPDATE_LEADERS_SCORE(610038, 101);

SELECT SCHOOL_ID, NAME_OF_SCHOOL, LEADERS_SCORE, LEADERS_ICON
FROM CHICAGO_PUBLIC_SCHOOLS
LIMIT 1;